# Site settings
title: Christopher Bynum
description: 'Personal Blog for Christopher A. Bynum'
url: 'http://localhost:4000'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Christopher Bynum'
  email: cbynum@gmail.command
  twitter_username: cbynum
  facebook_username: christopher.bynum71
  github_username:  cabynum
  linkedin_username:  christopher-bynum-6017942

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
