# Site settings
title: Levvel Legends
description: 'Engagement Journals for Levvel Consulting'
url: 'http://localhost:4000'
baseurl: '/levvel-legends/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Christopher Bynum'
  email: chris.bynum@levvel.io
  twitter_username: getlevvel
  facebook_username: getlevvel
  github_username:  getlevvel
  linkedin_username:  levvel-llc

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
